//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Info
    {
        public int ID { get; set; }
        public string Studentname { get; set; }
        public System.TimeSpan ATime { get; set; }
        public System.DateTime Date { get; set; }
        public string LecId { get; set; }
    }
}
